name: CI
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '12', '13', '14' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: rm -rf .yarnrc.yml
      - run: npm install -g yarn
      - run: yarn set version berry
      - run: yarn install
      - run: yarn test:unit
